reg sbyte,    System.SByte
reg byte,    System.Byte
reg short,   System.Int16
reg ushort,   System.UInt16
reg int,   System.Int32
reg uint,   System.UInt32
reg long,   System.Int64
reg ulong,   System.UInt64
reg float,   System.Single
reg double,   System.Double
reg decimal,   System.Decimal
reg bool,  System.Boolean
reg char,  System.Char
reg string, System.String